<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-09-30 19:51
=======
# Generated by Django 4.2.23 on 2025-10-12 15:20
>>>>>>> ac0aa81b (Fix annotation privacy logic and improve tests)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_chatmessage_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "permissions": (
                    ("permission_chatmessage", "permission chatmessage"),
                    ("publish_chatmessage", "publish chatmessage"),
                    ("create_chatmessage", "create chatmessage"),
                    ("read_chatmessage", "read chatmessage"),
                    ("update_chatmessage", "update chatmessage"),
                    ("remove_chatmessage", "delete chatmessage"),
                    ("comment_chatmessage", "comment chatmessage"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "permissions": (
                    ("permission_conversation", "permission conversation"),
                    ("publish_conversation", "publish conversation"),
                    ("create_conversation", "create conversation"),
                    ("read_conversation", "read conversation"),
                    ("update_conversation", "update conversation"),
                    ("remove_conversation", "delete conversation"),
                    ("comment_conversation", "comment conversation"),
                )
            },
        ),
    ]
