#!/usr/bin/env sh

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Add node to PATH (nvm should now be loaded)
export PATH="$NVM_DIR/versions/node/$(nvm version default | sed 's/v//')/bin:$PATH"

# Moving into the frontend directory and running 'lint-staged'
cd frontend
npx lint-staged
