# Generated by Django 4.2.23 on 2025-09-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0040_remove_annotation_annotation_created_by_only_one_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "permissions": (
                    ("permission_annotation", "permission annotation"),
                    ("create_annotation", "create annotation"),
                    ("read_annotation", "read annotation"),
                    ("update_annotation", "update annotation"),
                    ("remove_annotation", "delete annotation"),
                    ("comment_annotation", "comment annotation"),
                    ("publish_annotation", "publish relationship"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="relationship",
            options={
                "permissions": (
                    ("permission_relationship", "permission relationship"),
                    ("create_relationship", "create relationship"),
                    ("read_relationship", "read relationship"),
                    ("update_relationship", "update relationship"),
                    ("remove_relationship", "delete relationship"),
                    ("comment_relationship", "comment relationship"),
                    ("publish_relationship", "publish relationship"),
                )
            },
        ),
    ]
