# Generated by Django 4.2.23 on 2025-09-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0041_alter_annotation_options_alter_relationship_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotationlabeluserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="annotationlabeluserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="annotationlabeluserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="annotationlabeluserobjectpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="relationshipgroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="relationshipgroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="relationshipgroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="relationshipgroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="relationshipuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="relationshipuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="relationshipuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="relationshipuserobjectpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="AnnotationLabelGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="AnnotationLabelUserObjectPermission",
        ),
        migrations.DeleteModel(
            name="RelationshipGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="RelationshipUserObjectPermission",
        ),
    ]
