# Generated by Django 4.2.23 on 2025-09-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0042_alter_annotationlabeluserobjectpermission_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationlabel",
            options={
                "permissions": (
                    ("permission_annotationlabel", "permission Annotationlabel"),
                    ("publish_annotationlabel", "publish Annotationlabel"),
                    ("create_annotationlabel", "create Annotationlabel"),
                    ("read_annotationlabel", "read Annotationlabel"),
                    ("update_annotationlabel", "update Annotationlabel"),
                    ("remove_annotationlabel", "delete Annotationlabel"),
                    ("comment_annotationlabel", "comment Annotationlabel"),
                )
            },
        ),
    ]
