# Generated by Django 4.2.23 on 2025-10-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0042_alter_annotationlabeluserobjectpermission_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotationlabel",
            options={
                "permissions": (
                    ("permission_annotationlabel", "permission Annotationlabel"),
                    ("publish_annotationlabel", "publish Annotationlabel"),
                    ("create_annotationlabel", "create Annotationlabel"),
                    ("read_annotationlabel", "read Annotationlabel"),
                    ("update_annotationlabel", "update Annotationlabel"),
                    ("remove_annotationlabel", "delete Annotationlabel"),
                    ("comment_annotationlabel", "comment Annotationlabel"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="labelset",
            options={
                "permissions": (
                    ("permission_labelset", "Can permission labelset"),
                    ("publish_labelset", "Can publish labelset"),
                    ("create_labelset", "Can create labelset"),
                    ("read_labelset", "Can read labelset"),
                    ("update_labelset", "Can update labelset"),
                    ("remove_labelset", "Can delete labelset"),
                    ("comment_labelset", "Can comment labelset"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ("created",),
                "permissions": (
                    ("permission_note", "permission note"),
                    ("publish_note", "publish note"),
                    ("create_note", "create note"),
                    ("read_note", "read note"),
                    ("update_note", "update note"),
                    ("remove_note", "delete note"),
                    ("comment_note", "comment note"),
                ),
            },
        ),
    ]
