# Generated by Django 4.2.23 on 2025-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0043_alter_annotationlabel_options_alter_labelset_options_and_more",
        ),
        ("annotations", "0044_alter_labelset_options_alter_note_options"),
    ]

    operations = []
