# Generated by Django 4.2.23 on 2025-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_userexport_modified_userexport_user_lock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "permissions": (
                    ("permission_assignment", "permission assignment"),
                    ("publish_assignment", "publish assignment"),
                    ("create_assignment", "create assignment"),
                    ("read_assignment", "read assignment"),
                    ("update_assignment", "update assignment"),
                    ("remove_assignment", "delete assignment"),
                    ("comment_assignment", "comment assignment"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="userexport",
            options={
                "permissions": (
                    ("permission_userexport", "permission user export"),
                    ("publish_userexport", "publish user export"),
                    ("create_userexport", "create user export"),
                    ("read_userexport", "read user export"),
                    ("update_userexport", "update user export"),
                    ("remove_userexport", "delete user export"),
                    ("comment_userexport", "comment user export"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="userimport",
            options={
                "permissions": (
                    ("permission_userimport", "permission user import"),
                    ("publish_userimport", "publish user import"),
                    ("create_userimport", "create user import"),
                    ("read_userimport", "read user import"),
                    ("update_userimport", "update user import"),
                    ("remove_userimport", "delete user import"),
                    ("comment_userimport", "comment user import"),
                )
            },
        ),
    ]
