# Generated by Django 4.2.23 on 2025-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_assignment_options_alter_userexport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cookie_consent_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has accepted cookie consent",
                verbose_name="Cookie Consent Accepted",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cookie_consent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted cookie consent",
                null=True,
                verbose_name="Cookie Consent Date",
            ),
        ),
    ]
