# Generated by Django 4.2.20 on 2025-08-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extracts",
            "0019_rename_extracts_co_fieldse_c5f8d1_idx_extracts_co_fieldse_9e265e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datacell",
            name="llm_call_log",
            field=models.TextField(
                blank=True,
                help_text="Captured LLM message history for debugging extraction issues",
                null=True,
            ),
        ),
    ]
