# Generated by Django 4.2.23 on 2025-09-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0022_add_comprehensive_extract_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datacell",
            options={
                "permissions": (
                    ("permission_datacell", "permission datacell"),
                    ("create_datacell", "create datacell"),
                    ("read_datacell", "read datacell"),
                    ("update_datacell", "update datacell"),
                    ("remove_datacell", "delete datacell"),
                    ("comment_datacell", "comment datacell"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="extract",
            options={
                "permissions": (
                    ("permission_extract", "permission extract"),
                    ("create_extract", "create extract"),
                    ("read_extract", "read extract"),
                    ("update_extract", "update extract"),
                    ("remove_extract", "delete extract"),
                    ("comment_extract", "comment extract"),
                )
            },
        ),
    ]
