# Generated by Django 4.2.23 on 2025-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0023_alter_datacell_options_alter_extract_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={
                "permissions": (
                    ("permission_column", "permission column"),
                    ("create_column", "create column"),
                    ("read_column", "read column"),
                    ("update_column", "update column"),
                    ("remove_column", "delete column"),
                    ("comment_column", "comment column"),
                    ("publish_column", "publish column"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="datacell",
            options={
                "permissions": (
                    ("permission_datacell", "permission datacell"),
                    ("create_datacell", "create datacell"),
                    ("read_datacell", "read datacell"),
                    ("update_datacell", "update datacell"),
                    ("remove_datacell", "delete datacell"),
                    ("comment_datacell", "comment datacell"),
                    ("publish_datacell", "publish datacell"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="extract",
            options={
                "permissions": (
                    ("permission_extract", "permission extract"),
                    ("create_extract", "create extract"),
                    ("read_extract", "read extract"),
                    ("update_extract", "update extract"),
                    ("remove_extract", "delete extract"),
                    ("comment_extract", "comment extract"),
                    ("publish_extract", "publish extract"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="fieldset",
            options={
                "permissions": (
                    ("permission_fieldset", "permission fieldset"),
                    ("create_fieldset", "create fieldset"),
                    ("read_fieldset", "read fieldset"),
                    ("update_fieldset", "update fieldset"),
                    ("remove_fieldset", "delete fieldset"),
                    ("comment_fieldset", "comment fieldset"),
                    ("publish_fieldset", "publish fieldset"),
                )
            },
        ),
    ]
