# Generated by Django 4.2.23 on 2025-10-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0023_alter_datacell_options_alter_extract_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={
                "permissions": (
                    ("permission_column", "permission column"),
                    ("create_column", "create column"),
                    ("read_column", "read column"),
                    ("update_column", "update column"),
                    ("remove_column", "delete column"),
                    ("comment_column", "comment column"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="fieldset",
            options={
                "permissions": (
                    ("permission_fieldset", "permission fieldset"),
                    ("create_fieldset", "create fieldset"),
                    ("read_fieldset", "read fieldset"),
                    ("update_fieldset", "update fieldset"),
                    ("remove_fieldset", "delete fieldset"),
                    ("comment_fieldset", "comment fieldset"),
                )
            },
        ),
    ]
