# Generated by Django 4.2.23 on 2025-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0024_alter_column_options_alter_datacell_options_and_more"),
        ("extracts", "0024_alter_column_options_alter_fieldset_options"),
    ]

    operations = []
