# Generated by Django 4.2.23 on 2025-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0004_rename_userfeedbackobjectpermission_userfeedbackuserobjectpermission",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfeedback",
            options={
                "permissions": (
                    ("permission_userfeedback", "permission UserFeedback"),
                    ("publish_userfeedback", "publish UserFeedback"),
                    ("create_userfeedback", "create UserFeedback"),
                    ("read_userfeedback", "read UserFeedback"),
                    ("update_userfeedback", "update UserFeedback"),
                    ("remove_userfeedback", "delete UserFeedback"),
                    ("comment_userfeedback", "comment UserFeedback"),
                )
            },
        ),
    ]
