# Generated by Django 4.2.23 on 2025-09-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0019_corpus_slug_corpus_uniq_corpus_slug_per_creator_cs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpus",
            options={
                "base_manager_name": "objects",
                "ordering": ("created",),
                "permissions": (
                    ("permission_corpus", "permission corpus"),
                    ("publish_corpus", "publish corpus"),
                    ("create_corpus", "create corpus"),
                    ("read_corpus", "read corpus"),
                    ("update_corpus", "update corpus"),
                    ("remove_corpus", "delete corpus"),
                    ("comment_corpus", "comment corpus"),
                ),
            },
        ),
    ]
