# Generated by Django 4.2.23 on 2025-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0020_alter_corpus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpusaction",
            options={
                "permissions": (
                    ("permission_corpusaction", "permission corpusaction"),
                    ("publish_corpusaction", "publish corpusaction"),
                    ("create_corpusaction", "create corpusaction"),
                    ("read_corpusaction", "read corpusaction"),
                    ("update_corpusaction", "update corpusaction"),
                    ("remove_corpusaction", "delete corpusaction"),
                    ("comment_corpusaction", "comment corpusaction"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="corpusquery",
            options={
                "base_manager_name": "objects",
                "ordering": ("created",),
                "permissions": (
                    ("permission_corpusquery", "permission corpusquery"),
                    ("publish_corpusquery", "publish corpusquery"),
                    ("create_corpusquery", "create corpusquery"),
                    ("read_corpusquery", "read corpusquery"),
                    ("update_corpusquery", "update corpusquery"),
                    ("remove_corpusquery", "delete corpusquery"),
                    ("comment_corpusquery", "comment corpusquery"),
                ),
            },
        ),
    ]
