# Generated by Django 4.2.23 on 2025-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_document_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of the PDF file content for caching and integrity checks",
                max_length=64,
                null=True,
            ),
        ),
    ]
