# Generated by Django 4.2.23 on 2025-09-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_add_document_performance_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "permissions": (
                    ("permission_document", "permission document"),
                    ("publish_document", "publish document"),
                    ("create_document", "create document"),
                    ("read_document", "read document"),
                    ("update_document", "update document"),
                    ("remove_document", "delete document"),
                    ("comment_document", "comment document"),
                )
            },
        ),
    ]
