# Generated by Django 4.2.23 on 2025-10-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0021_alter_document_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentanalysisrow",
            options={
                "permissions": (
                    ("create_documentanalysisrow", "create DocumentAnalysisRow"),
                    ("read_documentanalysisrow", "read DocumentAnalysisRow"),
                    ("update_documentanalysisrow", "update DocumentAnalysisRow"),
                    ("remove_documentanalysisrow", "delete DocumentAnalysisRow"),
                    ("publish_documentanalysisrow", "publish DocumentAnalysisRow"),
                    (
                        "permission_documentanalysisrow",
                        "permission DocumentAnalysisRow",
                    ),
                    ("comment_documentanalysisrow", "comment DocumentAnalysisRow"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="documentrelationship",
            options={
                "permissions": (
                    (
                        "permission_documentrelationship",
                        "permission document relationship",
                    ),
                    ("publish_documentrelationship", "publish document relationship"),
                    ("create_documentrelationship", "create document relationship"),
                    ("read_documentrelationship", "read document relationship"),
                    ("update_documentrelationship", "update document relationship"),
                    ("remove_documentrelationship", "delete document relationship"),
                    ("comment_documentrelationship", "comment document relationship"),
                )
            },
        ),
    ]
