# Generated by Django 4.2.23 on 2025-09-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0014_add_analysis_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={
                "permissions": (
                    ("create_analysis", "create Analysis"),
                    ("read_analysis", "read Analysis"),
                    ("update_analysis", "update Analysis"),
                    ("remove_analysis", "delete Analysis"),
                    ("comment_analysis", "comment Analysis"),
                    ("publish_analysis", "publish Analysis"),
                    ("permission_analysis", "permission Analysis"),
                )
            },
        ),
    ]
