# Generated by Django 4.2.23 on 2025-10-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0014_add_analysis_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={
                "permissions": (
                    ("create_analysis", "create Analysis"),
                    ("read_analysis", "read Analysis"),
                    ("update_analysis", "update Analysis"),
                    ("remove_analysis", "delete Analysis"),
                    ("publish_analysis", "publish Analysis"),
                    ("permission_analysis", "permission Analysis"),
                    ("comment_analysis", "comment Analysis"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="analyzer",
            options={
                "permissions": (
                    ("permission_analyzer", "permission analyzer"),
                    ("publish_analyzer", "publish analyzer"),
                    ("create_analyzer", "create analyzer"),
                    ("read_analyzer", "read analyzer"),
                    ("update_analyzer", "update analyzer"),
                    ("remove_analyzer", "delete analyzer"),
                    ("comment_analyzer", "comment analyzer"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="gremlinengine",
            options={
                "permissions": (
                    ("permission_gremlinengine", "permission gremlin engine"),
                    ("publish_gremlinengine", "publish gremlin engine"),
                    ("create_gremlinengine", "create gremlin engine"),
                    ("read_gremlinengine", "read gremlin engine"),
                    ("update_gremlinengine", "update gremlin engine"),
                    ("remove_gremlinengine", "delete gremlin engine"),
                    ("comment_gremlinengine", "comment gremlin engine"),
                )
            },
        ),
    ]
