# Generated by Django 4.2.23 on 2025-09-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_alter_analysis_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyzer",
            options={
                "permissions": (
                    ("permission_analyzer", "permission analyzer"),
                    ("publish_analyzer", "publish analyzer"),
                    ("create_analyzer", "create analyzer"),
                    ("read_analyzer", "read analyzer"),
                    ("update_analyzer", "update analyzer"),
                    ("remove_analyzer", "delete analyzer"),
                    ("comment_analyzer", "comment analyzer"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="gremlinengine",
            options={
                "permissions": (
                    ("permission_gremlinengine", "permission gremlin engine"),
                    ("publish_gremlinengine", "publish gremlin engine"),
                    ("create_gremlinengine", "create gremlin engine"),
                    ("read_gremlinengine", "read gremlin engine"),
                    ("update_gremlinengine", "update gremlin engine"),
                    ("remove_gremlinengine", "delete gremlin engine"),
                    ("comment_gremlinengine", "comment gremlin engine"),
                )
            },
        ),
    ]
