# Generated by Django 4.2.23 on 2025-10-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_alter_analysis_options_alter_analyzer_options_and_more"),
        ("analyzer", "0016_alter_analyzer_options_alter_gremlinengine_options"),
    ]

    operations = []
